name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t macramgit/dvwa:latest .

  dependency_check:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - uses: actions/checkout@v3

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'DVWA'
          path: '.'
          format: 'HTML'

  semgrep_sast:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - uses: actions/checkout@v3

      - name: Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/php p/owasp-top-ten

  secrets_scan:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - uses: actions/checkout@v3

      - name: GitLeaks Secrets Scan
        uses: gitleaks/gitleaks-action@v2
