name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t macramgit/dvwa:latest .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'macramgit/dvwa:latest'
          severity: 'HIGH,CRITICAL'
