name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t macramgit/dvwa:latest .

  dependency_check:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - uses: actions/checkout@v3

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'DVWA'
          path: '.'
          format: 'HTML'

  semgrep_sast:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - uses: actions/checkout@v3

      - name: Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/php p/owasp-top-ten

  secrets_scan:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - uses: actions/checkout@v3

      - name: GitLeaks Secrets Scan
        uses: gitleaks/gitleaks-action@v2
  dast_scan:
    runs-on: ubuntu-latest
    needs: build_docker
    permissions:
      contents: read
      actions: read
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start DVWA container
        run: docker run -d -p 8080:80 --name dvwa-test macramgit/dvwa:latest

      - name: Wait for DVWA to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:8080 && break
            sleep 5
          done

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a'

      - name: Stop DVWA container
        run: docker stop dvwa-test
