name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t macramgit/dvwa:latest .
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'macramgit/dvwa:latest'
          severity: 'HIGH,CRITICAL'
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push macramgit/dvwa:latest

  dependency_check:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - uses: actions/checkout@v3
      - uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'DVWA'
          scan: '.'

  semgrep_sast:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/security-audit

  secrets_scan:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2

  dast_scan:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - uses: actions/checkout@v3
      - run: docker run -d -p 80:80 macramgit/dvwa:latest
      - uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:80'
